### PR TITLE
Fix placeholders in snippets

### PR DESCRIPTION
**Pull request by EmilyGraceSeville7cf**
Now they work properly:

image

### CODE REVIEW

**Comment by mihai-vlc** [comment]
I fixed this when I did the local testing.

Please try it in 1.1.0 and open a PR if any further updates are needed.

**Comment by EmilyGraceSeville7cf** [comment]
1.1.0 is not available for me now. 🤔 Just 1.0.3 can be installed.

**Comment by mihai-vlc** [comment]
it may have taken a few hours to propagate

**Comment by EmilyGraceSeville7cf** [comment]
Everything LGTM ;)

**Pull request closed without merging**
